server.port=8083
spring.application.name=report-service

# Diger servislerin adresleri (Docker network uzerinden)
chaos.service.url=http://chaos-service:8081
security.service.url=http://security-service:8082

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
